CI: bump ci-templates
This should fix the following problem when I targeted a MR to
branch 'color' in Sebastian's fork of wayland-protocols:

$ ci-fairy check-commits --signed-off-by --junit-xml=results.xml
Traceback (most recent call last):
  File "/usr/bin/ci-fairy", line 33, in <module>
    sys.exit(load_entry_point('ci-fairy==0.1', 'console_scripts', 'ci-fairy')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ci_fairy.py", line 1335, in check_commits
    for commit in repo.iter_commits(commit_range):
  File "/usr/lib/python3.9/site-packages/git/objects/commit.py", line 318, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/usr/lib/python3.9/site-packages/git/util.py", line 370, in finalize_process
    proc.wait(**kwargs)
  File "/usr/lib/python3.9/site-packages/git/cmd.py", line 447, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-list cifairy/color..HEAD --
  stderr: 'fatal: bad revision 'cifairy/color..HEAD'
'

Signed-off-by: Pekka Paalanen <pekka.paalanen@collabora.com>